apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: finserv-security-auditor-clusterrole
  labels:
    security.finserv.io/persona: auditor
rules:
- apiGroups: ["", "apps", "networking.k8s.io", "rbac.authorization.k8s.io"]
  resources: ["pods", "services", "deployments", "networkpolicies", "roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events", "namespaces"]
  verbs: ["get", "list", "watch"]
