apiVersion: v1
kind: Namespace
metadata:
  name: production-payments
  labels:
    environment: production
    domain: payments
    security.finserv.io/tier: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: production-risk
  labels:
    environment: production
    domain: risk-compliance
    security.finserv.io/tier: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: production-customer
  labels:
    environment: production
    domain: customer
    security.finserv.io/tier: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: production-platform
  labels:
    environment: production
    domain: platform
    security.finserv.io/tier: restricted
